### ISSUE TITLE
Unable to enable the plugin, getting the error "There was a problem loading this plugin"

### ISSUE THREAD

**Issue by scischool** [e3rd/zim-plugin-googletasks#22]
Hi. 
I wanted to use this plugin on Zim, but I get this error when trying to enable it:
`There was a problem loading this plugin`

This is the error that I get in the log:
```
ERROR: Could not load plugin googletasks
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/zim/gui/preferencesdialog.py", line 405, in __init__
    klass = self.plugins.get_plugin_class(key)
  File "/usr/lib/python3.10/site-packages/zim/plugins/__init__.py", line 469, in get_plugin_class
    mod = get_module(modname)
  File "/usr/lib/python3.10/site-packages/zim/utils.py", line 36, in get_module
    mod = __import__(name)
  File "/home/scischool/.local/share/zim/plugins/googletasks.py", line 14, in <module>
    import dateutil.parser
ModuleNotFoundError: No module named 'dateutil'
DEBUG: Loading description for plugin: arithmetic
DEBUG: Opening dialog "Preferences"
DEBUG: Loading description for plugin: googletasks
```

**Zim version 0.75.1**
**Python version 3.10.9**

**Comment by e3rd** [comment]
Thanks for pointing this out! The library is missing from the installation instructions.

Try `pip3 install --user dateutil`. Does it work now?

**Comment by e3rd** [comment]
O suppose this is ok then
